amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: base_footprint
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: map
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 0.5
    scan_topic: scan
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    use_sim_time: true
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
behavior_server:
  ros__parameters:
    assisted_teleop:
      plugin: nav2_behaviors/AssistedTeleop
    backup:
      plugin: nav2_behaviors/BackUp
    behavior_plugins:
    - spin
    - backup
    - drive_on_heading
    - assisted_teleop
    - wait
    costmap_topic: local_costmap/costmap_raw
    cycle_frequency: 10.0
    drive_on_heading:
      plugin: nav2_behaviors/DriveOnHeading
    footprint_topic: local_costmap/published_footprint
    global_frame: odom
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    robot_base_frame: base_link
    rotational_acc_lim: 3.2
    simulate_ahead_time: 2.0
    spin:
      plugin: nav2_behaviors/Spin
    transform_tolerance: 0.1
    use_sim_time: true
    wait:
      plugin: nav2_behaviors/Wait
bt_navigator:
  ros__parameters:
    bt_loop_duration: 10
    default_server_timeout: 20
    global_frame: map
    odom_topic: odom
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_smooth_path_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_assisted_teleop_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_drive_on_heading_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_globally_updated_goal_condition_bt_node
    - nav2_is_path_valid_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_truncate_path_local_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_path_expiring_timer_condition
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_goal_updated_controller_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_controller_cancel_bt_node
    - nav2_path_longer_on_approach_bt_node
    - nav2_wait_cancel_bt_node
    - nav2_spin_cancel_bt_node
    - nav2_back_up_cancel_bt_node
    - nav2_drive_on_heading_cancel_bt_node
    robot_base_frame: base_link
    use_sim_time: true
bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: true
bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: true
collision_monitor:
  ros__parameters:
    FootprintApproach:
      action_type: approach
      footprint_topic: local_costmap/published_footprint
      max_points: 5
      simulation_time_step: 0.1
      time_before_collision: 2.0
      type: polygon
      visualize: false
    PolygonSlow:
      action_type: slowdown
      max_points: 3
      points:
      - 1.0
      - 1.0
      - 1.0
      - -1.0
      - -0.0
      - -1.0
      - 0.0
      - 1.0
      polygon_pub_topic: polygon_slowdown
      slowdown_ratio: 1.0
      type: polygon
      visualize: true
    PolygonStop:
      action_type: stop
      max_points: 3
      points:
      - 0.2
      - 0.2
      - 0.2
      - -0.2
      - 0.0
      - -0.2
      - 0.0
      - 0.2
      polygon_pub_topic: polygon_stop
      type: polygon
      visualize: true
    base_frame_id: base_footprint
    cmd_vel_in_topic: cmd_vel_nav
    cmd_vel_out_topic: cmd_vel
    observation_sources:
    - scan
    odom_frame_id: odom
    polygons:
    - PolygonStop
    - PolygonSlow
    scan:
      topic: /scan
      type: scan
    source_timeout: 5.0
    stop_pub_timeout: 2.0
    transform_tolerance: 0.5
    use_sim_time: true
controller_server:
  ros__parameters:
    FollowPath:
      allow_reversing: false
      approach_velocity_scaling_dist: 1.5
      curvature_lookahead_dist: 0.25
      desired_linear_vel: 0.555
      lookahead_dist: 0.6
      lookahead_time: 1.5
      max_allowed_time_to_collision_up_to_carrot: 1.0
      max_angular_accel: 9999.0
      max_lookahead_dist: 0.9
      max_robot_pose_search_dist: 1.5
      min_approach_linear_velocity: 0.05
      min_lookahead_dist: 0.3
      plugin: nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      rotate_to_heading_angular_vel: 1.57
      rotate_to_heading_min_angle: 0.785
      transform_tolerance: 0.1
      use_collision_detection: true
      use_cost_regulated_linear_velocity_scaling: false
      use_fixed_curvature_lookahead: false
      use_interpolation: false
      use_regulated_linear_velocity_scaling: true
      use_rotate_to_heading: true
      use_velocity_scaled_lookahead_dist: false
    controller_frequency: 20.0
    controller_plugins:
    - FollowPath
    failure_tolerance: 0.3
    general_goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 4.0
    goal_checker_plugins:
    - general_goal_checker
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    progress_checker:
      movement_time_allowance: 10.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.5
    progress_checker_plugin: progress_checker
    use_sim_time: true
global_costmap:
  global_costmap:
    ros__parameters:
      always_send_full_costmap: true
      footprint: '[[-0.35, -0.2], [-0.35, 0.2], [0.15, 0.2], [0.15, -0.2]]'
      global_frame: map
      inflation_layer:
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
        plugin: nav2_costmap_2d::InflationLayer
      obstacle_layer:
        enabled: true
        observation_sources: scan
        plugin: nav2_costmap_2d::ObstacleLayer
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          topic: /vehicle4/scan
      plugins:
      - static_layer
      - obstacle_layer
      - inflation_layer
      publish_frequency: 1.0
      resolution: 0.05
      robot_base_frame: base_link
      static_layer:
        map_subscribe_transient_local: true
        plugin: nav2_costmap_2d::StaticLayer
      track_unknown_space: true
      update_frequency: 1.0
      use_sim_time: true
local_costmap:
  local_costmap:
    ros__parameters:
      always_send_full_costmap: true
      footprint: '[[-0.35, -0.2], [-0.35, 0.2], [0.15, 0.2], [0.15, -0.2]]'
      global_frame: odom
      height: 3
      inflation_layer:
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
        plugin: nav2_costmap_2d::InflationLayer
      plugins:
      - voxel_layer
      - inflation_layer
      publish_frequency: 2.0
      resolution: 0.05
      robot_base_frame: base_link
      rolling_window: true
      static_layer:
        map_subscribe_transient_local: true
        plugin: nav2_costmap_2d::StaticLayer
      update_frequency: 5.0
      use_sim_time: true
      voxel_layer:
        enabled: true
        mark_threshold: 0
        max_obstacle_height: 2.0
        observation_sources: scan
        origin_z: 0.0
        plugin: nav2_costmap_2d::VoxelLayer
        publish_voxel_map: true
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          topic: /scan
        z_resolution: 0.05
        z_voxels: 16
      width: 3
map_saver:
  ros__parameters:
    free_thresh_default: 0.25
    map_subscribe_transient_local: true
    occupied_thresh_default: 0.65
    save_map_timeout: 5.0
    use_sim_time: true
map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ''
planner_server:
  ros__parameters:
    GridBased:
      allow_unknown: true
      plugin: nav2_navfn_planner/NavfnPlanner
      tolerance: 0.5
      use_astar: false
    expected_planner_frequency: 20.0
    planner_plugins:
    - GridBased
    use_sim_time: true
robot_state_publisher:
  ros__parameters:
    use_sim_time: true
smoother_server:
  ros__parameters:
    simple_smoother:
      do_refinement: true
      max_its: 1000
      plugin: nav2_smoother::SimpleSmoother
      tolerance: 1.0e-10
    smoother_plugins:
    - simple_smoother
    use_sim_time: true
velocity_smoother:
  ros__parameters:
    deadband_velocity:
    - 0.0
    - 0.0
    - 0.0
    feedback: OPEN_LOOP
    max_accel:
    - 0.5
    - 0.0
    - 5.0
    max_decel:
    - -5.0
    - 0.0
    - -5.0
    max_velocity:
    - 1.666
    - 0.0
    - 6.28
    min_velocity:
    - 0.0
    - 0.0
    - -6.28
    odom_duration: 0.1
    odom_topic: odom
    scale_velocities: false
    smoothing_frequency: 20.0
    use_sim_time: true
    velocity_timeout: 1.0
waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    use_sim_time: true
    wait_at_waypoint:
      enabled: true
      plugin: nav2_waypoint_follower::WaitAtWaypoint
      waypoint_pause_duration: 200
    waypoint_task_executor_plugin: wait_at_waypoint
